### PR TITLE
[Feat] #229 카페 상세화면 url 정보를 통한 웹뷰 표출로직 추가

### LINKED ISSUE #229: 카페 상세화면 url 정보를 통한 웹뷰 표출로직 추가
# 🔍 Issue
이슈에 대한 내용을 적어주세요.
- [x] 카페 상세화면 url 정보를 선택 시 웹뷰를 표출로직을 추가해야합니다.

### PR DESCRIPTION
**Pull request by applebuddy**
## ☕️ PR 요약
- 카페 상세화면 url 정보를 통한 웹뷰 표출로직을 추가했습니다.

##### ✅ PR check list(PR 요청시 확인후 삭제해주세요)

```
- commit message가 적절한지 확인해주세요.
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue

close #229

### CODE REVIEW

**Review by NewHooon — COMMENTED** [review]
웹뷰 포출 로직 수행 시, 로그(error, warning)이 많이 발생하여 한번 확인 부탁드립니다🙏
시뮬레이터: IPad Pro(12.9 inch) 6th generation, iOS16

(1) url 링크를 통해 웹뷰를 실행할 때, 발생하는 로그(Error, warning)
`
2023-07-23 23:47:57.375972+0900 coffice[40255:1917169] [Security] This method should not be called on the main thread as it may lead to UI unresponsiveness.
`

(2) 웹뷰를 닫을 때, 발생하는 로그(Error, warning)
```swift
2023-07-23 23:47:59.423370+0900 coffice[40255:1922053] [assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
2023-07-23 23:47:59.423478+0900 coffice[40255:1922053] [ProcessSuspension] 0x1610c41e0 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=40777, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
2023-07-23 23:47:59.424918+0900 coffice[40255:1922053] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
2023-07-23 23:47:59.424996+0900 coffice[40255:1922053] [ProcessSuspension] 0x1610c4240 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess Suspended Assertion' for process with PID=40777, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}
2023-07-23 23:47:59.449107+0900 coffice[40255:1922053] [assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
2023-07-23 23:47:59.449183+0900 coffice[40255:1922053] [ProcessSuspension] 0x1610c4300 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess Suspended Assertion' for process with PID=40775, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
2023-07-23 23:48:29.385073+0900 coffice[40255:1917169] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

```

**Comment by applebuddy** [comment]
> 고생하셨습니다~! 웹뷰 포출 로직 수행 시, 로그(error, warning)이 많이 발생하여 한번 확인 부탁드립니다🙏 시뮬레이터: IPad Pro(12.9 inch) 6th generation, iOS16
> 
> (1) url 링크를 통해 웹뷰를 실행할 때, 발생하는 로그(Error, warning) `2023-07-23 23:47:57.375972+0900 coffice[40255:1917169] [Security] This method should not be called on the main thread as it may lead to UI unresponsiveness.`
> 
> (2) 웹뷰를 닫을 때, 발생하는 로그(Error, warning)
> 
> ```swift
> 2023-07-23 23:47:59.423370+0900 coffice[40255:1922053] [assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
> 2023-07-23 23:47:59.423478+0900 coffice[40255:1922053] [ProcessSuspension] 0x1610c41e0 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=40777, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
> 2023-07-23 23:47:59.424918+0900 coffice[40255:1922053] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
> 2023-07-23 23:47:59.424996+0900 coffice[40255:1922053] [ProcessSuspension] 0x1610c4240 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess Suspended Assertion' for process with PID=40777, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}
> 2023-07-23 23:47:59.449107+0900 coffice[40255:1922053] [assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
> 2023-07-23 23:47:59.449183+0900 coffice[40255:1922053] [ProcessSuspension] 0x1610c4300 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess Suspended Assertion' for process with PID=40775, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
> 2023-07-23 23:48:29.385073+0900 coffice[40255:1917169] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
> ```

이 문제가 iOS16 이상에서 재현되는 이미 인지하고 있던 이슈입니다. 다른 웹뷰 표출시에도 발생하고 있는문제가 추후 수정하는게 좋을 것 같아요 ㅠㅠ (구글링 좀 해봤는데, 버그일 가능성도 존재하는 것으로 보였어요...)

**Review by NewHooon — APPROVED** [review]
고생하셨습니다~

**Comment by applebuddy** [comment]
webView 이슈는 추후 수정하겠습니다. 위에 코멘트 참고해주세요!

**Pull request merged**
